Improved classProperty class not found. (#106)
If a class isn't found, then you get an exception like this:

java.lang.IllegalArgumentException: invalid class value for property 'io.aeron.benchmarks.message.transceiver', cause: io.aeron.benchmarks.aeron.EchoFanOutMessageTransceiver
       at io.aeron.benchmarks.Configuration.classProperty(Configuration.java:980)
       at io.aeron.benchmarks.Configuration.fromSystemProperties(Configuration.java:723)
       at io.aeron.benchmarks.LoadTestRig.main(LoadTestRig.java:391)

It isn't immediately clear that the class could not be found since that information is missing from the error.

This PR changes that by including the source exception.